### ISSUE TITLE
metron agent does not recover from intermittent consul outage

### ISSUE THREAD

**Issue by jsievers** [cloudfoundry/loggregator#175]
In various of our CF deployments (version 245, both openstack and AWS), we sporadically see various VMs no longer reporting via metron agent.

As an example, on hm9000 the stderr logs of metron_agent have messages like

```
2016/11/24 16:41:11 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:41:11 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:41:11 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:41:11 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:41:11 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:41:11 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:41:11 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:41:11 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
panic: No dopplers listening on [udp]

goroutine 54 [running]:
panic(0x960700, 0xc4204490d0)
        /var/vcap/data/packages/golang1.7/48ce7b3927e6f7e6576fff21a7dc9d22b7ba9c62.1-e04b1de537d7998b284ea1d9ad820d48b6ddf15a/src/runtime/panic.go:500 +0x1a1
metron/clientreader.Read(0xc420234030, 0xc420448ca0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /var/vcap/data/compile/metron_agent/loggregator/src/metron/clientreader/client_reader.go:17 +0x393
main.initializeDopplerPool.func1(0xc420234030, 0xc420096780, 0xc4200730e0, 0xc4200c5c20, 0xc4202f0140, 0xc420234060)
        /var/vcap/data/compile/metron_agent/loggregator/src/metron/main.go:205 +0x169
created by main.initializeDopplerPool
        /var/vcap/data/compile/metron_agent/loggregator/src/metron/main.go:209 +0x63d
2016/11/24 16:42:02 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:42:02 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:42:02 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:42:02 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:42:02 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:42:02 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:42:02 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:42:02 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
panic: No dopplers listening on [udp]

goroutine 69 [running]:
panic(0x960700, 0xc420434970)
        /var/vcap/data/packages/golang1.7/48ce7b3927e6f7e6576fff21a7dc9d22b7ba9c62.1-e04b1de537d7998b284ea1d9ad820d48b6ddf15a/src/runtime/panic.go:500 +0x1a1
metron/clientreader.Read(0xc420246030, 0xc420434590, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /var/vcap/data/compile/metron_agent/loggregator/src/metron/clientreader/client_reader.go:17 +0x393
main.initializeDopplerPool.func1(0xc420246030, 0xc420096640, 0xc420073200, 0xc4200c5700, 0xc420304200, 0xc420246060)
        /var/vcap/data/compile/metron_agent/loggregator/src/metron/main.go:205 +0x169
created by main.initializeDopplerPool
        /var/vcap/data/compile/metron_agent/loggregator/src/metron/main.go:209 +0x63d
2016/11/24 16:46:33 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:46:33 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:46:33 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:46:33 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:46:33 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:46:33 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:46:33 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
2016/11/24 16:46:33 RuntimeStats: failed to emit: EventWriter: No envelope writer set (see SetWriter)
```

There were several monit restarts following the panic lines above. The last monit restart was unable to SetWriter,
but did not exit the process. As a result the stdout logs of metron_agent are full of messages like

```
{"timestamp":1480424571.683505297,"process_id":6298,"source":"metron","log_level":"warn","message":"EventMarshaller: Write called while byteWriter is nil","data":null,"file":"/var/vcap/data/compile/metron_agent/loggregator/src/metron/writers/eventmarshaller/event_marshaller.go","line":59,"method":"metron/writers/eventmarshaller.(*EventMarshaller).Write"}
{"timestamp":1480424572.683612823,"process_id":6298,"source":"metron","log_level":"warn","message":"EventMarshaller: Write called while byteWriter is nil","data":null,"file":"/var/vcap/data/compile/metron_agent/loggregator/src/metron/writers/eventmarshaller/event_marshaller.go","line":59,"method":"metron/writers/eventmarshaller.(*EventMarshaller).Write"}
```

Digging into the details, we found that just before the first metron_agent panic above, we find in the consul_agent logs of the same VM:

```
==> Log data will now stream in as it occurs:

    2016/11/24 16:40:59 [INFO] serf: EventMemberJoin: hm9000-z1-0 <REDACTED>
    2016/11/24 16:40:59 [WARN] manager: No servers available
    2016/11/24 16:40:59 [ERR] agent: failed to sync remote state: No known Consul servers
    2016/11/24 16:41:00 [WARN] agent: Check 'service:hm9000' is now critical


    2016/11/24 16:41:03 [WARN] agent: Check 'service:hm9000' is now critical
    2016/11/24 16:41:06 [WARN] agent: Check 'service:hm9000' is now critical
    2016/11/24 16:41:09 [INFO] agent: Synced check 'service:hm9000'
```

The consul_agent recovered in the meantime, e.g. we can successfully `dig cf-etcd.service.cf.internal`
However metron_agent is still in error state but does not exit the process, so the problem can go unnoticed for a long time until you notice that logs or metrics are missing.

Workaround is to monit restart both consul_agent and metron_agent.

**Comment by jsievers** [comment]
this looks similar to issue #169

**Comment by jsievers** [comment]
It turned out that the root cause was a corrupted etcd cluster.
After following https://github.com/cloudfoundry-incubator/etcd-release#failed-deploys-upgrades-split-brain-scenarios-etc most metron agents recovered.

A few VMs still needed a manual `monit restart metron_agent`

Up to you if you want to keep this open to make metron_agent more robust against etcd failing and then recovering.

**Comment by ahevenor** [comment]
Thanks for confirming @jsievers. We have seen similar issues. We have plans to improve our service discovery and key value store that should address this in a future release.
